1. При помощи Python реализуйте функцию с именем `new_arr(arr)`, которая заменяет значения на `0` на границе и оставляет неизменными значения внутри. Возвращать функция должна измененный массив. Например, если дан массив вида
$$
\begin{array}{|c|c|с|}
\hline        
\textbf{1} & \textbf{2} & \textbf{3}\\ \hline        
\textbf{4} & \textbf{5} & \textbf{6}\\ \hline
\textbf{7} & \textbf{8} & \textbf{9}\\ \hline 
\textbf{10} & \textbf{11} & \textbf{12}\\ \hline        
\end{array}
$$
, то результирующий массив
$$
\begin{array}{|c|c|с|}
\hline        
\textbf{0} & \textbf{0} & \textbf{0}\\ \hline        
\textbf{0} & \textbf{5} & \textbf{0}\\ \hline
\textbf{0} & \textbf{8} & \textbf{0}\\ \hline   
\textbf{0} & \textbf{0} & \textbf{0}\\ \hline              
\end{array}
$$


In [4]:
import numpy as np

def new_arr(arr):
    # Проверяем, является ли входной массив двумерным
    if len(arr.shape) != 2:
        raise ValueError("Входной массив должен быть двумерной матрицей")

    # Создаем копию исходного массива, чтобы не изменять оригинал
    new_array = np.copy(arr)
    
    # Заменяем значения на границе массива на 0
    new_array[0, :] = 0          # Верхняя граница
    new_array[-1, :] = 0         # Нижняя граница
    new_array[:, 0] = 0          # Левая граница
    new_array[:, -1] = 0         # Правая граница

    return new_array

# Пример использования
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
])

result = new_arr(arr)
print(result)

[[0 0 0]
 [0 5 0]
 [0 8 0]
 [0 0 0]]


2. При помощи Python реализуйте функцию с именем `new_arr(m, n)`, которая формирует массив `(3,3)`, значения которого - последовательность чисел от `m` до `n` c одинаковым шагом. На вход функция получает `m`, `n`. Например, `new_arr(51,59)` возвращает:
$$
\begin{array}{|c|c|с|}
\hline        
\textbf{51.} & \textbf{52.} & \textbf{53.}\\ \hline        
\textbf{54.} & \textbf{55.} & \textbf{56.}\\ \hline
\textbf{57.} & \textbf{58.} & \textbf{59.}\\ \hline        
\end{array}
$$

In [5]:
import numpy as np

def new_arr(m, n):
    if m > n: # если min > max, меняем местами
        min1 = m 
        m = n
        n = min1
    return np.linspace(m, n, num =  9).reshape(3,3) 

# Пример использования
result = new_arr(51, 59)
print(result)

[[51. 52. 53.]
 [54. 55. 56.]
 [57. 58. 59.]]


3. При помощи Python реализуйте функцию с именем `new_arr(size)`, которая создает массив указанной размерности, значения которого `0` и `1` (целые числа), расположенные в шахматном порядке. Первый элемент массива равен `1`. Например, `new_arr(3)` возвращает:
$$
\begin{array}{|c|c|с|}
\hline        
\textbf{1} & \textbf{0} & \textbf{1}\\ \hline        
\textbf{0} & \textbf{1} & \textbf{0}\\ \hline
\textbf{1} & \textbf{0} & \textbf{1}\\ \hline       
\end{array}
$$


In [9]:
import numpy as np

def new_arr(size):
    if 0 > size: size = 0 # если размер отрицательный, возврашаем матрицу 0 размера
    arr = np.zeros([size,size])
    arr[::2,::2] = 1 
    arr[1::2,1::2] = 1
    return arr

# Пример использования
result = new_arr(3)
print(result)

[[1. 0. 1.]
 [0. 1. 0.]
 [1. 0. 1.]]


4. Из списка ниже выберите ОДИН правильный метод преобразования массива. `append(), reshape(), transpose(), flatten(), expand_dims()`

Какой из методов может изменить размерность одномернго массива с (N,) на (N,1)?
Какой из методов может изменить размерность c (3,4) на (2,6)?
Какой из методов может из многомерного массива вернуть одномерный?

In [10]:
# Какой из методов может изменить размерность одномернго массива с (N,) на (N,1)?
import numpy as np
arr = np.array([1, 2, 3])  # размерность (3,)
new_arr = np.expand_dims(arr, axis=1)  # размерность (3,1)
print(new_arr)

[[1]
 [2]
 [3]]


In [11]:
# Какой из методов может изменить размерность c (3,4) на (2,6)?
import numpy as np
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])  # размерность (3,4)
new_arr = np.reshape(arr, (2, 6))  # размерность (2,6)
print(new_arr)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [12]:
# Какой из методов может из многомерного массива вернуть одномерный?
import numpy as np
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])  # размерность (3,3)
new_arr = arr.flatten()  # размерность (9,)
print(new_arr)

[1 2 3 4 5 6 7 8 9]
