1. Дан следующий трехмерный массив `arr`:
$$
\begin{array}{|c|c|с|}
\hline        
\textbf{1} & \textbf{2} & \textbf{3}\\ \hline        
\textbf{4} & \textbf{5} & \textbf{6}\\ \hline
\textbf{7} & \textbf{8} & \textbf{9}\\ \hline       
\end{array}
$$
При помощи Python и метода `.size` необходимо вывести размерность получаемых ниже элементов массива.
Выведите размерность для `arr[:2,1:]`
Выведите размерность для `arr[2]`
Выведите размерность для `arr[:, :2]`
Выведите размерность для `arr[1, :2]`

In [3]:
import numpy as np

# Создаем трехмерный массив
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Размерность для arr[:2, 1:]
subarray1 = arr[:2, 1:]
print("Размерность arr[:2, 1:]:", subarray1.shape, ", Количество элементов:", subarray1.size)

# Размерность для arr[2]
subarray2 = arr[2]
print("Размерность arr[2]:", subarray2.shape, ", Количество элементов:", subarray2.size)

# Размерность для arr[:, :2]
subarray3 = arr[:, :2]
print("Размерность arr[:, :2]:", subarray3.shape, ", Количество элементов:", subarray3.size)

# Размерность для arr[1, :2]
subarray4 = arr[1, :2]
print("Размерность arr[1, :2]:", subarray4.shape, ", Количество элементов:", subarray4.size)

Размерность arr[:2, 1:]: (2, 2) , Количество элементов: 4
Размерность arr[2]: (3,) , Количество элементов: 3
Размерность arr[:, :2]: (3, 2) , Количество элементов: 6
Размерность arr[1, :2]: (2,) , Количество элементов: 2


2. Напишите разультаты выполнения кода, написанного на языке Python.

Выведите размерность `.size` массива `np.append(np.zeros((2,2)),np.array([[1,2],[4,5]]))`:
Выведите количество строк массива `np.append(np.zeros((2,2)),np.array([[1,2],[4,5]]),axis = 1)`:
Выведите значение последнего элемента массива `np.sort(np.append(np.array([[1,2],[3,0]]),np.array([[1,2],[5,4]]),axis = 0),axis = 0)`:
Сколько элементов будет выведено в результате суммирования `np.append(np.array([[1,2],[3,0]]),np.array([[1,2],[5,4]]),axis = 0).sum(axis = 1)`:

In [9]:
# Выведите размерность `.size` массива `np.append(np.zeros((2,2)),np.array([[1,2],[4,5]]))`:
print(np.append(np.zeros((2,2)),np.array([[1,2],[4,5]])).size)

# Выведите количество строк массива `np.append(np.zeros((2,2)),np.array([[1,2],[4,5]]),axis = 1)`:
print(np.append(np.zeros((2,2)),np.array([[1,2],[4,5]]),axis = 1))

# Выведите значение последнего элемента массива `np.sort(np.append(np.array([[1,2],[3,0]]),np.array([[1,2],[5,4]]),axis = 0),axis = 0)`:
print(np.sort(np.append(np.array([[1,2],[3,0]]),np.array([[1,2],[5,4]]),axis = 0),axis = 0))

# Сколько элементов будет выведено в результате суммирования `np.append(np.array([[1,2],[3,0]]),np.array([[1,2],[5,4]]),axis = 0).sum(axis = 1)`:
print(np.append(np.array([[1,2],[3,0]]),np.array([[1,2],[5,4]]),axis = 0).sum(axis = 1))

8
[[0. 0. 1. 2.]
 [0. 0. 4. 5.]]
[[1 0]
 [1 2]
 [3 2]
 [5 4]]
[3 3 3 9]


3. Пусть даны две квадратные матрицы `a, b` одинаковой размерности. При помощи Python реализуйте функцию с именем `vertical_concat(a, b)`, которая принимает на вход данные матрицы и соединяет их вдоль строк (в результате должна получиться матрица с таким же числом столбцов, как в исходных, и вдвое большим количеством строк). Например, если исходные матрицы
```
a = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
b = np.array([
    [1, 1, 1],
    [1, 1, 1]
]), 
```
тогда результат
```
np.array([
    [1, 2, 3],
    [4, 5, 6],
    [1, 1, 1],
    [1, 1, 1]
])     
```


In [10]:
import numpy as np

def vertical_concat(a, b):
    # Проверим, что обе матрицы имеют одинаковую размерность
    if a.shape != b.shape:
        raise ValueError("Матрицы должны быть одинаковой размерности")
    
    # Соединяем матрицы вдоль строк (оси 0)
    result = np.vstack((a, b))
    return result

# Пример использования
a = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

b = np.array([
    [1, 1, 1],
    [1, 1, 1]
])

result = vertical_concat(a, b)
print(result)

[[1 2 3]
 [4 5 6]
 [1 1 1]
 [1 1 1]]


4. Пусть дана прямоугольная матрица `a`. При помощи Python реализуйте функцию с именем `arr_min(a)`, которая выводит минимальные элементы из каждой строки данной матрицы. Например,
```
a = np.array([
    [3, 6, 3],
    [4, 8, 19]
])
```
тогда результат `array([ 3, 4])`

In [11]:
import numpy as np

def arr_min(a):
    # Если входной массив не двухмерный, выбрасываем исключение
    if len(a.shape) != 2:
        raise ValueError("Входной массив должен быть двумерной матрицей")
    
    # Используем np.min с указанием оси 1 для нахождения минимального элемента в каждой строке
    result = np.min(a, axis=1)
    return result

# Пример использования
a = np.array([
    [3, 6, 3],
    [4, 8, 19]
])

result = arr_min(a)
print(result)

[3 4]
